### ISSUE TITLE
Scan multiple images or output to same sarif file

### ISSUE THREAD

**Issue by jmthomas** [aquasecurity/trivy-action#197]
I have an existing github [action](https://github.com/OpenC3/cosmos/blob/main/.github/workflows/playwright.yml) which builds all my containers and tests them. I'd like to try adding trivy scanning and upload the results to Github. However, it appears you can only scan a single container at a time. That's fine (although it gets verbose to specify the same options every time) but even if I create multiple sarif files I can only load one to Github due to:

    Run github/codeql-action/upload-sarif@v2
    Uploading results
      Processing sarif files: ["trivy-node.sarif"]
      Error: Aborting upload: only one run of the codeql/analyze or codeql/upload-sarif actions is allowed per job per tool/category. The easiest fix is to specify a unique value for the `category` input. If .runs[].automationDetails.id is specified in the sarif file, that will take precedence over your configured `category`. Category: (.github/workflows/playwright.yml:openc3-build-test-scan/) Tool: (Trivy)
      Error: Aborting upload: only one run of the codeql/analyze or codeql/upload-sarif actions is allowed per job per tool/category. The easiest fix is to specify a unique value for the `category` input. If .runs[].automationDetails.id is specified in the sarif file, that will take precedence over your configured `category`. Category: (.github/workflows/playwright.yml:openc3-build-test-scan/) Tool: (Trivy)
          at validateUniqueCategory (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:375:[19](https://github.com/OpenC3/cosmos/actions/runs/4012606001/jobs/6919768669#step:20:20))
          at uploadFiles (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:250:5)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:136:12)
          at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:48:30)
          at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:70:9)

I tried creating separate files for each run but that didn't work because the file didn't exist. How do you scan multiple containers and upload the results to Github?

**Comment by jmthomas** [comment]
The trick appears to be adding a category to each upload:

      - name: Run Trivy on image ruby
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/openc3inc/openc3-ruby:latest"
          format: "sarif"
          output: "trivy-ruby.sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
          security-checks: "vuln"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: "openc3-ruby"
          sarif_file: "trivy-ruby.sarif"

As long as these are unique the uploads all work.
