### ISSUE TITLE
Panic: inconsistent map element types

### ISSUE THREAD

**Issue by jw-maynard** [aquasecurity/trivy-action#290]
Running the trivy-action causes a panic and the action fails due to `panic: inconsistent map element types (cty.Object(map[string]cty.Type{"arn":cty.String, "endpoint":cty.NilType, "for_each":cty.Object(map[string]cty.Type{"arn":cty.String, "for_each":cty.NilType, "id":cty.String, "name":cty.NilType}), "id":cty.String, "protocol":cty.String, "topic_arn":cty.NilType}) then cty.Object(map[string]cty.Type{"arn":cty.String, "endpoint":cty.String, "for_each":cty.Object(map[string]cty.Type{"arn":cty.String, "for_each":cty.NilType, "id":cty.String, "name":cty.NilType}), "id":cty.String, "protocol":cty.String, "topic_arn":cty.NilType}))`

I set the action up to scan IaC (Terraform) code as specified here: https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-infrastructure-as-code

```
Run aquasecurity/trivy-action@master
  with:
    scan-type: config
    hide-progress: false
    format: sarif
    output: trivy-results.sarif
    exit-code: 0
    ignore-unfixed: true
    severity: CRITICAL,HIGH
    scan-ref: .
    vuln-type: os,library
    list-all-pkgs: false
/usr/bin/docker run --name bb60[2](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:2)a404cc46d97dc4407970541fedafdef88_0a70b2 --label bb602a --workdir /github/workspace --rm -e "INPUT_SCAN-TYPE" -e "INPUT_HIDE-PROGRESS" -e "INPUT_FORMAT" -e "INPUT_OUTPUT" -e "INPUT_EXIT-CODE" -e "INPUT_IGNORE-UNFIXED" -e "INPUT_SEVERITY" -e "INPUT_IMAGE-REF" -e "INPUT_INPUT" -e "INPUT_SCAN-REF" -e "INPUT_VULN-TYPE" -e "INPUT_TEMPLATE" -e "INPUT_SKIP-DIRS" -e "INPUT_SKIP-FILES" -e "INPUT_CACHE-DIR" -e "INPUT_TIMEOUT" -e "INPUT_IGNORE-POLICY" -e "INPUT_LIST-ALL-PKGS" -e "INPUT_SCANNERS" -e "INPUT_TRIVYIGNORES" -e "INPUT_ARTIFACT-TYPE" -e "INPUT_GITHUB-PAT" -e "INPUT_TRIVY-CONFIG" -e "INPUT_TF-VARS" -e "INPUT_LIMIT-SEVERITIES-FOR-SARIF" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/corporate_infrastructure/corporate_infrastructure":"/github/workspace" bb602a:404cc46d97dc4407970541fedafdef88  "-a config" "-b sarif" "-c " "-d 0" "-e true" "-f os,library" "-g CRITICAL,HIGH" "-h trivy-results.sarif" "-i " "-j ." "-k " "-l " "-m " "-n " "-o " "-p false" "-q " "-r false" "-s " "-t " "-u " "-v " "-x " "-z "
Building SARIF report with options:  --exit-code  0 .
panic: inconsistent map element types (cty.Object(map[string]cty.Type{"arn":cty.String, "endpoint":cty.NilType, "for_each":cty.Object(map[string]cty.Type{"arn":cty.String, "for_each":cty.NilType, "id":cty.String, "name":cty.NilType}), "id":cty.String, "protocol":cty.String, "topic_arn":cty.NilType}) then cty.Object(map[string]cty.Type{"arn":cty.String, "endpoint":cty.String, "for_each":cty.Object(map[string]cty.Type{"arn":cty.String, "for_each":cty.NilType, "id":cty.String, "name":cty.NilType}), "id":cty.String, "protocol":cty.String, "topic_arn":cty.NilType}))

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.MapVal(0xc00[3](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:3)95eb28)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.13.0/cty/value_init.go:220 +0x[4](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:4)0e
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*evaluator).expandBlockForEaches(0xc001c73a40, {0xc003488600, 0x23, 0x0?})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/evaluator.go:32[5](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:5) +0x4df
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*evaluator).expandBlocks(0x78dc240?, {0xc002ff3a00?, 0x78dc240?, 0xc003e20c30?})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/evaluator.go:207 +0x30
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*evaluator).EvaluateAll(0xc001c73a40, {0x9b30ee8, 0xc000fbc930})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/evaluator.go:152 +0x2e5
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*Parser).EvaluateAll(0xc0024129a0, {0x9b30ee8, 0xc000fbc930})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/parser.go:313 +0x[6](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:6)b[7](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:7)
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc002d2ab00, {0x9b30ee[8](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:8), 0xc000fbc[9](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:9)30}, {0x9a70260?, 0xc0018085d0}, {0x9a58958, 0x1})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/scanner.go:226 +0x5d0
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform.(*Scanner).ScanFS(0x0?, {0x9b30ee8?, 0xc000fbc930?}, {0x9a70260?, 0xc0018085d0?}, {0x9a58958?, 0x2a?})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/scanner.go:143 +0x46
github.com/aquasecurity/trivy/pkg/misconf.(*Scanner).Scan(0xc002599770, {0x9b30ee8, 0xc000fbc930}, {0x9a70260?, 0xc0029ae6f0?})
	/home/runner/work/trivy/trivy/pkg/misconf/scanner.go:147 +0x190
github.com/aquasecurity/trivy/pkg/fanal/analyzer/config.(*Analyzer).PostAnalyze(0xc00091b320, {0x9b30ee8?, 0xc000fbc930?}, {{0x9a70260?, 0xc0029ae6f0?}, {0x9?, 0x0?}})
	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/config/config.go:45 +0x46
github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.PostAnalyze({{0xc002c9e140, 0x3, 0x4}, {0xc0016[10](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:10)900, 0x7, 0x8}, 0xc00271d9e0}, {0x9b30ee8, 0xc000fbc930}, 0xc00175fe50, ...)
	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:491 +0x2ad
github.com/aquasecurity/trivy/pkg/fanal/artifact/local.Artifact.Inspect({{0x7fff[11](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:11)37ebd4, 0x1}, {0x7f840d39f0d0, 0xc0022d9fb0}, {{{0x0, 0x0, 0x0}, {0xc001790280, 0x3, 0x4}}, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/fanal/artifact/local/fs.go:163 +0x48f
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x0, 0x0, 0x0}, {0xc0022d9f00, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/scanner/scan.go:146 +0x103
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, {0xc002d00240, ...}, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:704 +0x3b7
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact(_, {_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:267 +0xba
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanFS(_, {_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:215 +0xc5
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).ScanFilesystem(_, {_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:195 +0x211
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, {0xc002d00240, ...}, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:428 +0x4ff
github.com/aquasecurity/trivy/pkg/commands.NewConfigCommand.func2(0xc000c6c900, {0xc002435400, 0x1, 0x8})
	/home/runner/work/trivy/trivy/pkg/commands/app.go:683 +0x2f2
github.com/spf[13](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:14)/cobra.(*Command).execute(0xc000c6c900, {0xc002435380, 0x8, 0x8})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc003545800)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x8537fe3?)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.run()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:35 +0x198
main.main()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:[17](https://github.com/PlayQ-DevOps/corporate_infrastructure/actions/runs/7144942591/job/19459592733?pr=393#step:4:18) +0x13
```

**Comment by simar7** [comment]
Thanks we are working on a fix https://github.com/aquasecurity/trivy-iac/pull/60

**Comment by shrutijodevops** [comment]
+1

**Comment by el-chazmo** [comment]
is there an ETA for this fix? I see the PR is ready https://github.com/aquasecurity/trivy-iac/pull/60 but not reviewed yet

**Comment by el-chazmo** [comment]
+1

**Comment by httpdss** [comment]
fix got to master but im still having same issue.

**Comment by jw-maynard** [comment]
@simar7 this is still and issue for me too. Here's a recent run

```
Building SARIF report with options:  --exit-code  0 .
panic: inconsistent map element types (cty.Object(map[string]cty.Type{"arn":cty.String, "batch_size":cty.Number, "event_source_arn":cty.String, "for_each":cty.Map(cty.Object(map[string]cty.Type{"arn":cty.String, "for_each":cty.Object(map[string]cty.Type{"arn":cty.String, "bucket":cty.NilType, "for_each":cty.Set(cty.String), "id":cty.NilType}), "id":cty.String, "name":cty.String, "redrive_policy":cty.NilType})), "function_name":cty.NilType, "id":cty.String}) then cty.Object(map[string]cty.Type{"arn":cty.String, "batch_size":cty.Number, "event_source_arn":cty.String, "for_each":cty.Map(cty.Object(map[string]cty.Type{"arn":cty.String, "for_each":cty.Object(map[string]cty.Type{"arn":cty.String, "bucket":cty.NilType, "for_each":cty.Set(cty.String), "id":cty.NilType}), "id":cty.String, "name":cty.String, "redrive_policy":cty.NilType})), "function_name":cty.String, "id":cty.String}))

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.MapVal(0xc003504b28)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.13.0/cty/value_init.go:220 +0x40e
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*evaluator).expandBlockForEaches(0xc002b27500, {0xc0036dfa00, 0x36, 0x0?})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/evaluator.go:325 +0x4df
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*evaluator).expandBlocks(0x78dc240?, {0xc0032a4400?, 0x78dc240?, 0xc002d6c120?})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/evaluator.go:207 +0x30
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*evaluator).EvaluateAll(0xc002b27500, {0x9b30ee8, 0xc0009511f0})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/evaluator.go:[15](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:16)2 +0x2e5
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform/parser.(*Parser).EvaluateAll(0xc001d63ce0, {0x9b30ee8, 0xc0009511f0})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/parser/parser.go:313 +0x6b7
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc002a70100, {0x9b30ee8, 0xc0009511f0}, {0x9a70260?, 0xc003358558}, {0x9a58958, 0x1})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/scanner.go:226 +0x5d0
github.com/aquasecurity/trivy-iac/pkg/scanners/terraform.(*Scanner).ScanFS(0x0?, {0x9b30ee8?, 0xc0009511f0?}, {0x9a70260?, 0xc003358558?}, {0x9a58958?, 0x2a?})
	/home/runner/go/pkg/mod/github.com/aquasecurity/trivy-iac@v0.7.0/pkg/scanners/terraform/scanner.go:143 +0x46
github.com/aquasecurity/trivy/pkg/misconf.(*Scanner).Scan(0xc002f62150, {0x9b30ee8, 0xc0009511f0}, {0x9a70260?, 0xc000ad3c68?})
	/home/runner/work/trivy/trivy/pkg/misconf/scanner.go:147 +0x190
github.com/aquasecurity/trivy/pkg/fanal/analyzer/config.(*Analyzer).PostAnalyze(0xc001810d00, {0x9b30ee8?, 0xc0009511f0?}, {{0x9a70260?, 0xc000ad3c68?}, {0x9?, 0x0?}})
	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/config/config.go:45 +0x46
github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.PostAnalyze({{0xc00258b800, 0x3, 0x4}, {0xc00103c900, 0x7, 0x8}, 0xc0027cefc0}, {0x9b30ee8, 0xc0009511f0}, 0xc001257e50, ...)
	/home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:491 +0x2ad
github.com/aquasecurity/trivy/pkg/fanal/artifact/local.Artifact.Inspect({{0x7ffc645a2bce, 0x1}, {0x7f41be7eda18, 0xc002efc220}, {{{0x0, 0x0, 0x0}, {0xc001286240, 0x3, 0x4}}, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/fanal/artifact/local/fs.go:[16](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:17)3 +0x48f
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x0, 0x0, 0x0}, {0xc002efc[17](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:18)0, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/scanner/scan.go:146 +0x103
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, {0xc001382ce0, ...}, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:704 +0x3b7
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact(_, {_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:267 +0xba
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanFS(_, {_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:215 +0xc5
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).ScanFilesystem(_, {_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, ...}, ...})
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:[19](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:20)5 +0x[21](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:22)1
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{{0x84d167a, 0xa}, 0x0, 0x1, 0x0, 0x0, 0x45d964b800, {0xc001382ce0, ...}, ...}, ...}, ...)
	/home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:428 +0x4ff
github.com/aquasecurity/trivy/pkg/commands.NewConfigCommand.func2(0xc001102300, {0xc000d[22](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:23)500, 0x1, 0x8})
	/home/runner/work/trivy/trivy/pkg/commands/app.go:683 +0x2f2
github.com/spf13/cobra.(*Command).execute(0xc00110[23](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:24)00, {0xc000d22380, 0x8, 0x8})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a60c00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x8537fe3?)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.run()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:[35](https://github.com/PlayQ-DevOps/platform_infrastructure/actions/runs/7333402739/job/19968790898?pr=1769#step:4:36) +0x198
main.main()
	/home/runner/work/trivy/trivy/cmd/trivy/main.go:17 +0x13
```

**Comment by jw-maynard** [comment]
Looks like we just need this PR to land: #291

**Comment by el-chazmo** [comment]
> Looks like we just need this PR to land: #291

Any update on when it might land? still experiencing this issue

**Comment by simar7** [comment]
The team was away for holidays. We will work on it this week and have a new release available soon.

**Comment by simar7** [comment]
Released https://github.com/aquasecurity/trivy-action/releases/tag/0.16.1
